# .github/workflows/low-stock-email.yml
name: Email on Low Stock

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/stock.csv'
  workflow_dispatch:

env:
  STOCK_PATH: docs/stock.csv
  DEFAULT_MIN_STOCK: "10"
  LOGO_PATH: docs/assets/parcsafe-logo.png

jobs:
  check-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build HTML email with all items where stockQty < minStock
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          python3 scripts/gen_low_stock_email.py --current "${{ env.STOCK_PATH }}" --logo-path "${{ env.LOGO_PATH }}"
          COUNT=$(cat count.txt 2>/dev/null || echo 0)
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"

      - name: Send email (Office365 SMTP)
        if: steps.detect.outputs.count != '0'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          secure: true                # STARTTLS amb 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "LOW STOCK ALERT — Parcsafe Warehouse"
          from: "\"STOCK ALERT!!\" <${{ secrets.SMTP_USERNAME }}>"    # mateixa adreça que l'username
          to: ${{ secrets.TO_EMAILS || secrets.TO_EMAIL || secrets.MAIL_TO }}
          html_body: file://email_body.html
