name: Email on Low Stock

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/stock.csv'
  workflow_dispatch:

env:
  STOCK_PATH: docs/stock.csv
  DEFAULT_MIN_STOCK: "2"

jobs:
  check-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2   # <- NECESSARI per poder llegir HEAD^ (CSV anterior)

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Prepare previous CSV (if any)
        id: prev
        shell: bash
        run: |
          set -euo pipefail
          # Intenta extreure el CSV anterior a aquest commit
          if git show HEAD^:${{ env.STOCK_PATH }} > prev.csv 2>/dev/null; then
            echo "has_prev=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_prev=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Detect newly low-stock items and build email body
        id: detect
        shell: bash
        run: |
          set -euo pipefail

          CSV="${{ env.STOCK_PATH }}"
          if [ ! -f "$CSV" ]; then
            echo "CSV not found at $CSV" >&2
            echo "count=0" >> "$GITHUB_OUTPUT"
            printf "Stock file not found: %s\n" "$CSV" > email_body.txt
            exit 0
          fi

          # Executa l’script Python comparant present vs. anterior (si existeix prev.csv)
          python3 scripts/gen_low_stock_email.py --current "$CSV" --prev prev.csv

          COUNT=$(cat count.txt 2>/dev/null || echo 0)
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"

      - name: Send email (SMTP)
        if: steps.detect.outputs.count != '0'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Low Stock Alert — ${{ github.repository }}"
          from: ${{ secrets.FROM_EMAIL }}
          to: ${{ secrets.TO_EMAILS || secrets.TO_EMAIL }}
          secure: ${{ secrets.SMTP_SECURE || 'false' }}   # 587→false, 465→true
          body: file://email_body.txt                    # <-- FIX: file://
