name: Email on Low Stock

on:
  push:
    branches:
      - main
    paths:
      - 'stock.csv'          # ← ajusta a la teva ruta si no és a l'arrel
  workflow_dispatch:          # ← per provar-lo manualment

jobs:
  check-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Debug: show changed files in this push"
        run: |
          echo "REF=$GITHUB_REF"
          echo "SHA=$GITHUB_SHA"
          echo "BEFORE=${{ github.event.before }}"
          git diff --name-status "${{ github.event.before }}" "${{ github.sha }}" || true

      - name: Extract before/after CSV
        id: files
        run: |
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"

          # Si el fitxer no existia abans, crea CSV amb només capçalera
          if git cat-file -e "$BEFORE:stock.csv" 2>/dev/null; then
            git show "$BEFORE:stock.csv" > before.csv
          else
            if [ -f stock.csv ]; then
              head -n1 stock.csv > before.csv
            else
              echo "drawerCode,productName,productCode,description,stockQty,minStock" > before.csv
            fi
          fi

          git show "$AFTER:stock.csv" > after.csv

      - name: Detect low-stock rows
        id: detect
        run: |
          node <<'NODE'
          const fs = require('fs');

          function parseCSV(path){
            const raw = fs.readFileSync(path,'utf8').trim();
            if (!raw) return {headers:[], rows:[]};
            const lines = raw.split(/\r?\n/).filter(Boolean);
            const headers = lines[0].split(',').map(h=>h.trim());
            const rows = lines.slice(1).map(line=>{
              const cols = line.split(',').map(v=>v.trim());
              const obj = {};
              headers.forEach((h,i)=>obj[h]=cols[i]??'');
              obj.stockQty = Number(obj.stockQty ?? 0);
              obj.minStock = obj.minStock !== undefined && obj.minStock !== '' ? Number(obj.minStock) : 10;
              return obj;
            });
            return {headers, rows};
          }

          const before = parseCSV('before.csv');
          const after  = parseCSV('after.csv');

          const mapBefore = new Map(before.rows.map(r => [r.drawerCode, r]));
          const offenders = [];

          for (const row of after.rows){
            const prev = mapBefore.get(row.drawerCode);
            const prevQty = prev ? Number(prev.stockQty) : null;
            const nowQty = Number(row.stockQty);
            const min    = Number(row.minStock ?? 10);

            const wasOk = prevQty === null ? true : prevQty >= min;
            if (Number.isFinite(nowQty) && Number.isFinite(min) && nowQty < min && wasOk){
              offenders.push({
                drawerCode: row.drawerCode,
                productName: row.productName || '(no name)',
                productCode: row.productCode || '',
                newQty: nowQty,
                minStock: min
              });
            }
          }

          if (offenders.length){
            let body = `Low Stock Alert\n\nThe following product(s) dropped below minimum:\n\n`;
            for (const o of offenders){
              body += `• ${o.drawerCode} — ${o.productName} (${o.productCode}) → ${o.newQty} (min ${o.minStock})\n`;
            }
            body += `\nRepo: ${process.env.GITHUB_REPOSITORY}\nCommit: ${process.env.GITHUB_SHA}\nBy: ${process.env.GITHUB_ACTOR}\n`;
            fs.writeFileSync('email_body.txt', body, 'utf8');
            console.log(body);
          }

          // ➜ passa la sortida al següent pas
          fs.appendFileSync(process.env.GITHUB_OUTPUT, `count=${offenders.length}\n`);
          NODE

      - name: Send email (SMTP)
        if: steps.detect.outputs.count != '0'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Low Stock Alert — ${{ github.repository }}"
          from: ${{ secrets.FROM_EMAIL }}
          to: ${{ secrets.TO_EMAILS || secrets.TO_EMAIL }}
          secure: true
          body: file:email_body.txt
