name: Stock & Info change emails

on:
  push:
    paths:
      - "docs/stock.csv"

jobs:
  diff-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (need previous commit too)
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Ensure Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Calcula canvis i escriu:
      #  - low_stock=true/false
      #  - info_changed=true/false
      #  - low_stock_email.txt (si cal)
      #  - info_update_email.html (si cal)
      - name: Build email decision & bodies
        id: diff
        shell: bash
        run: |
          set -euo pipefail
          git show HEAD:docs/stock.csv  > current.csv
          git show HEAD^:docs/stock.csv > previous.csv
          python3 scripts/diff_mail.py

      - name: Debug SMTP connectivity
        if: always()
        run: |
          echo "Testing smtp.office365.com:587"
          nc -vz smtp.office365.com 587 || true
          echo | openssl s_client -connect smtp.office365.com:587 -starttls smtp -servername smtp.office365.com -brief || true

      # LOW STOCK (text)
      - name: Send LOW STOCK email (Office365)
        if: steps.diff.outputs.low_stock == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "LOW STOCK — Parcsafe Warehouse"
          from: ${{ secrets.SMTP_USERNAME }}
          to: ${{ secrets.MAIL_TO }}
          body: file://low_stock_email.txt

      # PRODUCT INFO UPDATED (HTML)
      - name: Send PRODUCT INFO UPDATED email (Office365)
        if: steps.diff.outputs.info_changed == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "PRODUCT INFO UPDATED — Parcsafe Warehouse"
          from: ${{ secrets.SMTP_USERNAME }}
          to: ${{ secrets.MAIL_TO }}
          html_body: file://info_update_email.html
